apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: magalu-registry-secret
      restartPolicy: Always
      containers:
        - name: backend
          image: $(IMAGE)
          ports:
            - containerPort: $(TARGET_PORT)
              protocol: TCP
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
