apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: $(SERVICE_PORT)
      targetPort: $(TARGET_PORT)
