services:
  app:
    container_name: fastfood-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DB_URL=mysql://root:docker@fastfood-db:3306/fastfood
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
    networks:
      fastfood-network:
        ipv4_address: 172.30.0.10
    command: npm run start:prod
  db:
    container_name: fastfood-db
    restart: always
    image: mysql:8.4
    env_file:
      - .env
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      fastfood-network:
        ipv4_address: 172.30.0.20

volumes:
  mysqldata:

networks:
  fastfood-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
