apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastfood-app
  template:
    metadata:
      labels:
        app: fastfood-app
    spec:
      containers:
        - name: fastfood-app
          image: lealfelipealves/fastfood-app:latest
          ports:
            - containerPort: 3333
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
