apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  IMAGE: "container-registry.br-se1.magalu.cloud/fastfood-backend/xpe-pa-cc-backend-app:latest"
  TARGET_PORT: "3333"
  SERVICE_PORT: "80"